/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.ImageIcon;

/**
 *
 * @author Aluno
 */
public class EscolhaHorario extends javax.swing.JFrame {
    private String horas;
    
    /**
     * Creates new form EscolhaHorario
     */
    public EscolhaHorario() {
        initComponents();
        carregarImagem();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jB1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBH1 = new javax.swing.JButton();
        jBH2 = new javax.swing.JButton();
        jBH3 = new javax.swing.JButton();
        jBH6 = new javax.swing.JButton();
        jBH5 = new javax.swing.JButton();
        jBH4 = new javax.swing.JButton();
        jBH9 = new javax.swing.JButton();
        jBH8 = new javax.swing.JButton();
        jBH7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("ESCOLHA DE HORÁRIOS");

        jB1.setText("<-- Voltar");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jLabel2.setText("HOJE");

        jLabel3.setText("AMANHÃ");

        jLabel4.setText("DEPOIS DE AMANHÃ");

        jBH1.setText("14:30");
        jBH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBH1ActionPerformed(evt);
            }
        });

        jBH2.setText("15:45");
        jBH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBH2ActionPerformed(evt);
            }
        });

        jBH3.setText("17:30");
        jBH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBH3ActionPerformed(evt);
            }
        });

        jBH6.setText("17:30");
        jBH6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBH6ActionPerformed(evt);
            }
        });

        jBH5.setText("15:45");
        jBH5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBH5ActionPerformed(evt);
            }
        });

        jBH4.setText("14:30");
        jBH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBH4ActionPerformed(evt);
            }
        });

        jBH9.setText("17:30");
        jBH9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBH9ActionPerformed(evt);
            }
        });

        jBH8.setText("15:45");
        jBH8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBH8ActionPerformed(evt);
            }
        });

        jBH7.setText("14:30");
        jBH7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBH7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBH7)
                        .addGap(29, 29, 29)
                        .addComponent(jBH8)
                        .addGap(30, 30, 30)
                        .addComponent(jBH9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBH4)
                        .addGap(29, 29, 29)
                        .addComponent(jBH5)
                        .addGap(30, 30, 30)
                        .addComponent(jBH6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jB1)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(jBH1)
                            .addGap(29, 29, 29)
                            .addComponent(jBH2)
                            .addGap(30, 30, 30)
                            .addComponent(jBH3))))
                .addGap(56, 306, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(264, 264, 264))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBH1)
                    .addComponent(jBH2)
                    .addComponent(jBH3))
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBH4)
                    .addComponent(jBH5)
                    .addComponent(jBH6))
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBH7)
                    .addComponent(jBH8)
                    .addComponent(jBH9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jB1)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        // TODO add your handling code here:
        
        EscolhaFilme frame = new EscolhaFilme();
        
        frame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jB1ActionPerformed

    private void jBH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBH1ActionPerformed

        
        
        
        Poltronas frame = new Poltronas();
        
        frame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jBH1ActionPerformed

    private void jBH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBH2ActionPerformed
Poltronas frame = new Poltronas();
        
        frame.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBH2ActionPerformed

    private void jBH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBH3ActionPerformed
Poltronas frame = new Poltronas();
        
        frame.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBH3ActionPerformed

    private void jBH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBH4ActionPerformed
      Poltronas frame = new Poltronas();
        
        frame.setVisible(true);
        this.dispose();
  // TODO add your handling code here:
    }//GEN-LAST:event_jBH4ActionPerformed

    private void jBH5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBH5ActionPerformed
Poltronas frame = new Poltronas();
        
        frame.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBH5ActionPerformed

    private void jBH6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBH6ActionPerformed
Poltronas frame = new Poltronas();
        
        frame.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBH6ActionPerformed

    private void jBH7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBH7ActionPerformed
Poltronas frame = new Poltronas();
        
        frame.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBH7ActionPerformed

    private void jBH8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBH8ActionPerformed
Poltronas frame = new Poltronas();
        
        frame.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBH8ActionPerformed

    private void jBH9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBH9ActionPerformed
Poltronas frame = new Poltronas();
        
        frame.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBH9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jBH1;
    private javax.swing.JButton jBH2;
    private javax.swing.JButton jBH3;
    private javax.swing.JButton jBH4;
    private javax.swing.JButton jBH5;
    private javax.swing.JButton jBH6;
    private javax.swing.JButton jBH7;
    private javax.swing.JButton jBH8;
    private javax.swing.JButton jBH9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

private void carregarImagem() {
        
    }

    public String getHoras() {
        return horas;
    }


}
