
package telas;


import database.PedidoDAO;
import java.util.ArrayList;
/**
 *
 * @author Aluno
 */
public class Pagamentos extends javax.swing.JFrame {
        private String filme;
        private String horario;
        private String dia;
        private String metodoPagamento;
        private ArrayList<String> poltronas;

    /**
     * Creates new form Tela_5
     */
    public Pagamentos(String filme, String horario, ArrayList<String> poltronasSelecionadas, String dia) {
        initComponents();
        this.filme = filme;
        this.horario = horario;
        this.poltronas = poltronasSelecionadas;
        this.dia = dia;
        
        
        System.out.println("Horário: " + horario);
        System.out.println("Poltronas: " + String.join(", ",  poltronas));
        System.out.println("Dia: " + dia);
        
    }

    private Pagamentos() {
    initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Credito = new javax.swing.JButton();
        Debito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Como pagar:");

        Credito.setText("Crédito");
        Credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditoActionPerformed(evt);
            }
        });

        Debito.setText("Débito");
        Debito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Credito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(Debito)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Credito)
                    .addComponent(Debito))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditoActionPerformed
        metodoPagamento = "Crédito";
        System.out.println("Método de pagamento selecionado: " + metodoPagamento);
        
        
        PedidoDAO dao = new PedidoDAO();
        dao.salvarPedido(filme, horario, String.join(", ", poltronas), dia, metodoPagamento);
        
        VCPagou frame = new VCPagou(metodoPagamento);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CreditoActionPerformed

    private void DebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitoActionPerformed
        metodoPagamento = "Débito";
        System.out.println("Método de pagamento selecionado: " + metodoPagamento);
        
        PedidoDAO dao = new PedidoDAO();
        dao.salvarPedido(filme, horario, String.join(", ", poltronas), dia, metodoPagamento);
        VCPagou frame = new VCPagou(metodoPagamento);
        
        frame.setVisible(true);
        this.dispose();   
        
    }//GEN-LAST:event_DebitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Credito;
    private javax.swing.JButton Debito;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
